search/urls.py
from django.urls import path
from . import views

app_name = "search"

urlpatterns = [
    path('', views.index, name='index'),
    path('player_detail/<str:id>', views.player_detail, name='player_detail'),
    path('team_detail/<str:id>', views.team_detail, name='team_detail'),
]

semweb_b16/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from SPARQLWrapper import SPARQLWrapper, JSON

def index(request):
    if request.method == "POST":
        input = {}
        input['category'] = request.POST.get('category')
        input['input-a'] = request.POST.get('input-a')

        if input['category'] == 'Country':
            results = search_country(input['input-a'])
            return render(request, 'main.html', {'results': results, 'category': input['category']})
        elif input['category'] == 'League':
            results = search_league(input['input-a'])
            return render(request, 'main.html', {'results': results, 'category': input['category']})
        elif input['category'] == 'Team':
            results = search_team(input['input-a'])
            return render(request, 'main.html', {'results': results, 'category': input['category']})
        elif input['category'] == 'Player':
            results = search_player(input['input-a'])
            return render(request, 'main.html', {'results': results, 'category': input['category']})

    return render(request, 'main.html')  
    
def search_country(input):
    searchText = input
    print(searchText)
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')
    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        SELECT ?country ?countryName
        WHERE {
            ?country a o:country .
            ?country p:countryName ?countryName .
            FILTER (
                (REGEX(?countryName, ".*''' + searchText + '''.*", "i"))
            )
        }
    ''')
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    for result in results['results']['bindings']:
        print(result['country']['value'])
        print('''Country: ''' + result['country']['value'] + '\n' + 'Country Name: ' + result['countryName']['value'] + '\n\n')

    return results

def search_league(input):
    searchText = input
    print(searchText)
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')
    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        SELECT ?league ?leagueName ?country ?countryName
        WHERE {
            ?league a o:league .
            ?league p:leagueName ?leagueName .
            ?league p:isLeagueOfCountry ?country .
            ?country p:countryName ?countryName .
            FILTER (
                (REGEX(?leagueName, ".*''' + searchText + '''.*", "i")) ||
                (REGEX(?countryName, ".*''' + searchText + '''.*", "i"))
            )
        }
    ''')
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    for result in results['results']['bindings']:
        print('League: ' + result['league']['value'] + '\n' + 'League Name: ' + result['leagueName']['value'] + '\n' + 'Country: ' + result['country']['value'] + '\n' + 'Country Name: ' + result['countryName']['value'] + '\n\n')

    return results

def search_player(input):
    searchText = input
    print(searchText)
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')
    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        SELECT ?player ?playerName ?birthday ?height ?weight
        WHERE {
            ?player a o:player .
            ?player p:playerName ?playerName .
            ?player p:birthday ?birthday .
            ?player p:height ?height .
            ?player p:weight ?weight .
            FILTER (
                (REGEX(?playerName, ".*''' + searchText + '''.*", "i"))
            )
        }
    ''')
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    playerListTxt = ''
    for result in results['results']['bindings']:
        playerListTxt += 'Player: ' + result['player']['value'] + '\n' + 'Player Name: ' + result['playerName']['value'] + '\n' + 'Birthday: ' + result['birthday']['value'][:10] + '\n' + 'Height (cm): ' + result['height']['value'] + '\n' + 'Weight (lbs): ' + result['weight']['value'] + '\n\n'
        result['birthday']['value'] = result['birthday']['value'][:10]
        result['player']['value'] = result['player']['value'][35:]

    return results

def search_team(input):
    searchText = input
    print(searchText)
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')
    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        SELECT ?team ?teamLongName ?teamShortName
        WHERE {
            ?team a o:team .
            ?team p:teamLongName ?teamLongName .
            ?team p:teamShortName ?teamShortName .
            FILTER (
                (REGEX(?teamLongName, ".*''' + searchText + '''.*", "i")) ||
                (REGEX(?teamShortName, ".*''' + searchText + '''.*", "i"))
            )
        }
    ''')
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    playerListTxt = ''
    for result in results['results']['bindings']:
        playerListTxt += 'Team: ' + result['team']['value'] + '\n' + 'Team Long Name: ' + result['teamLongName']['value'] + '\n' + 'Team Short Name: ' + result['teamShortName']['value'] + '\n\n'
        result['team']['value'] = result['team']['value'][33:]

    return results

def player_detail(request, id):
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')

    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        PREFIX r_player: <http://example.org/resource/player/>

        SELECT ?playerName ?birthday ?height ?weight ?overallRating ?dateRated
        WHERE {
            r_player:''' + id + ''' p:playerName ?playerName .
            r_player:''' + id + ''' p:birthday ?birthday .
            r_player:''' + id + ''' p:height ?height .
            r_player:''' + id + ''' p:weight ?weight .
            OPTIONAL {
                {
                    SELECT ?playerAttribute ?dateRated
                    WHERE {
                        ?playerAttribute p:isAttributeOfPlayer r_player:''' + id + ''' .
                        ?playerAttribute p:isPlayerAttributeOfDate ?dateRated .
                    }
                    ORDER BY DESC (?dateRated) LIMIT 1
                }
                ?playerAttribute p:overallRating ?overallRating .
            }
        }
        LIMIT 1
    ''')
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()
    result = results['results']['bindings'][0]

    attText = ''
    try:
        attText += '\n\nLatest FIFA Overall Rating: ' + result['overallRating']['value'] + '\n'
        attText += 'Date Rated: ' + result['dateRated']['value'][:10]
    except:
        print('FIFA Player Attribute not found')
        attText = '\n\nFIFA Player Attribute not found'

    playerDbLink = result['playerName']['value'].replace(' ', '_')
    dbSparql = SPARQLWrapper('http://dbpedia.org/sparql')

    dbSparql.setQuery('''
        PREFIX dbr: <http://dbpedia.org/resource/>
        PREFIX dbo: <http://dbpedia.org/ontology/>

        SELECT ?abstract ?thumbnail
        WHERE {
            dbr:''' + playerDbLink + ''' dbo:abstract ?abstract .
            dbr:''' + playerDbLink + ''' dbo:thumbnail ?thumbnail .
            FILTER langMatches(lang(?abstract), "en")
        }
    ''')
    dbSparql.setReturnFormat(JSON)
    dbResults = dbSparql.query().convert()

    dbText = ''
    try:
        dbResult = dbResults['results']['bindings'][0]
        dbText += '\n\nDBPedia Link: http://dbpedia.org/resource/' + playerDbLink + '\n' + 'Description:\n' + dbResult['abstract']['value'] + '\n\n' + 'Image: ' + dbResult['thumbnail']['value']
    except:
        print("DBPedia link not found")
        dbText = '\n\nDBPedia link not found'

    playerTxt = 'Player: http://example.org/resource/player/' + id + '\n' + 'Player Name: ' + result['playerName']['value'] + '\n\n' + 'Birthday: ' + result['birthday']['value'][:10] + '\n' + 'Height (cm): ' + result['height']['value'] + '\n' + 'Weight (lbs): ' + result['weight']['value'] + attText + dbText
    # return render(request, 'player_detail.html',{})
    return HttpResponse(playerTxt, content_type='text/plain')

def team_detail(request, id):
    sparql = SPARQLWrapper('http://localhost:9999/blazegraph/sparql')

    sparql.setQuery('''
        PREFIX o: <http://example.org/ontology/>
        PREFIX p: <http://example.org/property/>

        PREFIX r_team: <http://example.org/resource/team/>

        SELECT
            ?teamLongName
            ?teamShortName
            ?buildUpPlaySpeed
            ?buildUpPlayDribbling
            ?buildUpPlayPassing
            ?buildUpPlayPositioning
            ?chanceCreationPassing
            ?chanceCreationCrossing
            ?chanceCreationShooting
            ?chanceCreationPositioning
            ?defencePressure
            ?defenceAggression
            ?defenceTeamWidth
            ?defenceDefenderLine
            ?dateRated
        WHERE {
            r_team:''' + id + ''' p:teamLongName ?teamLongName .
            r_team:''' + id + ''' p:teamShortName ?teamShortName .
            OPTIONAL {
                {
                    SELECT ?teamAttribute ?dateRated
                    WHERE {
                        ?teamAttribute p:isAttributeOfTeam r_team:''' + id + ''' .
                        ?teamAttribute p:isTeamAttributeOfDate ?dateRated .
                    }
                    ORDER BY DESC (?dateRated) LIMIT 1
                }
                ?teamAttribute p:buildUpPlaySpeed ?buildUpPlaySpeed .
                ?teamAttribute p:buildUpPlayDribbling ?buildUpPlayDribbling .
                ?teamAttribute p:buildUpPlayPassing ?buildUpPlayPassing .
                ?teamAttribute p:buildUpPlayPositioning ?buildUpPlayPositioning .

search/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EURO bOWLa</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Boogaloo&family=Roboto+Condensed&display=swap" rel="stylesheet">

    <!-- CSS File -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <div class="title-page d-flex flex-column justify-content-center">
        <div class="container">
            <h1 class="title text-center" style="font-size: 60px; font-weight: bold;">EURO bOWLa</h1>
            <form class="mt-5 d-flex justify-content-center" method="post">
                {% csrf_token %}
                <select required class="form-control mx-3" style="width: 200px;" name='category'>
                    <option value="" disabled selected hidden>What to search?</option>
                    <option>Country</option>
                    <option>League</option>
                    <option>Team</option>
                    <option>Player</option>
                </select>
                <input type="text" style="width: 300px;" class="form-control mr-2" placeholder="e.g Manchester United" name='input-a' value="">
                <button type="submit" style="margin-left: 10px;" class="btn mr-2">Search</button>
            </form>
            <div class="d-flex justify-content-center">
                <div class="lds-ellipsis" id="spinner" hidden>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
    {% if results %}
    <div class="result-page pt-5" id="result">
        {% if category == 'Country' %}
        <div class="container">
            <div class="d-flex flex-column">
                {% for country in results.results.bindings %}
                <div class="d-flex justify-content-between">
                    <div class="card mb-3 w300">
                        <div class="card-body">
                            <div class="mx-2">{{ country.country.value }}</div>
                            <h5>{{ country.countryName.value }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% elif category == 'League' %}
        <div class="container">
            <div class="d-flex flex-column">
                {% for league in results.results.bindings %}
                <div class="d-flex justify-content-between">
                    <div class="card mb-3 w300">
                        <div class="card-body">
                            <div class="mx-2">{{ league.league.value }}</div>
                            <h5>{{ league.leagueName.value }}</h5>
                            <div class="mx-2">{{ league.countryName.value }}</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% elif category == 'Team' %}
        <div class="container">
            <div class="d-flex flex-column">
                {% for team in results.results.bindings %}
                <div class="d-flex justify-content-between">
                    <div class="card mb-3 w300">
                        <div class="card-body">
                            <div class="mx-2">http://example.org/resource/team/{{ team.team.value }}</div>
                            <h5>{{ team.teamLongName.value }}</h5>
                            <h5>{{ team.teamShortName.value }}</h5>
                            <div class="d-flex justify-content-center">
                                <a href="{% url 'search:team_detail' team.team.value %}" class="btn mt-3">See Details</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% elif category == 'Player' %}
        <div class="container">
            <div class="d-flex flex-column">
                {% for player in results.results.bindings %}
                <div class="d-flex justify-content-between">
                    <div class="card mb-3 w300">
                        <div class="card-body">
                            <div class="mx-2">http://example.org/resource/player/{{ player.player.value }}</div>
                            <h5>{{ player.playerName.value }}</h5>
                            <div class="d-flex justify-content-center">
                                <button class="btn mt-3" data-toggle="modal" data-target="#modal">See Details</button>
                            </div>
                        </div>
                    </div>
                </div>

                 <!-- Modal -->
                <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div class="mx-2">http://example.org/resource/player/{{ player.player.value }}</div>
                                <h5>{{ player.playerName.value }}</h5>
                            </div>
                            <div class="modal-body">
                                <div class="info-element mt-3">
                                    <div class="info-title">Birthday</div>
                                    <div class="text-justify">{{ player.birthday.value }}</div>
                                </div>
                                <div class="info-element mt-3">
                                    <div class="info-title">Height</div>
                                    <div class="text-justify">{{ player.height.value }} cm</div>
                                </div>
                                <div class="info-element mt-3">
                                    <div class="info-title">Weight</div>
                                    <div class="text-justify">{{ player.weight.value }} lbs</div>
                                </div>
                                <!-- <div class="info-element mt-3">
                                    <button class="btn mt-3">More</button>
                                </div> -->
                                <div class="info-element mt-3">
                                    <a href="{% url 'search:player_detail' player.player.value %}" class="btn mt-3">More</a>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
    {% endif %}
</body>
</html>